// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_character_character_ from "./routes/(platform)/character/[character].tsx";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_favorites from "./routes/(platform)/favorites.tsx";
import * as $_platform_house_house_ from "./routes/(platform)/house/[house].tsx";
import * as $_platform_profile from "./routes/(platform)/profile.tsx";
import * as $_platform_search from "./routes/(platform)/search.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_nuevofavorito from "./routes/api/nuevofavorito.ts";
import * as $api_quitarfavorito from "./routes/api/quitarfavorito.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $IslaCharacter from "./islands/IslaCharacter.tsx";
import * as $IslaFavoritesCharacters from "./islands/IslaFavoritesCharacters.tsx";
import * as $IslaLogin from "./islands/IslaLogin.tsx";
import * as $IslaProfile from "./islands/IslaProfile.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/character/[character].tsx":
      $_platform_character_character_,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/favorites.tsx": $_platform_favorites,
    "./routes/(platform)/house/[house].tsx": $_platform_house_house_,
    "./routes/(platform)/profile.tsx": $_platform_profile,
    "./routes/(platform)/search.tsx": $_platform_search,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/nuevofavorito.ts": $api_nuevofavorito,
    "./routes/api/quitarfavorito.ts": $api_quitarfavorito,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/IslaCharacter.tsx": $IslaCharacter,
    "./islands/IslaFavoritesCharacters.tsx": $IslaFavoritesCharacters,
    "./islands/IslaLogin.tsx": $IslaLogin,
    "./islands/IslaProfile.tsx": $IslaProfile,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
